### ISSUE TITLE
Invalid validation for the git version

### ISSUE THREAD

**Issue by OlegFedko** [MarkPflug/MSBuildGitHash#1]
I failed to build my solution with error:

> C:\repo\packages\MSBuildGitHash.0.2.0\build\MSBuildGitHash.targets(29,5): error : MSBuildGitHash hash value starting with 'Roll_1.0-232-g474e3a4-dirty' was invalid.

Where "Roll_1.0" is a label used some time ago in history.
It seems that MSBuildGitHash doesn't work with labels.

It is said that I can somehow customize the validation but there is no any wiki how to do it,

**Comment by OlegFedko** [comment]
I found workaround - just cut the label with **--match ""** parameter.

So I added file MyMSBuildGitHash.props:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <MSBuildGitHashCommand>git describe --long --always --dirty --match ""</MSBuildGitHashCommand>
    </PropertyGroup>
</Project>
```

and added it to my csproj file (see second line):
```xml
  <Import Project="..\packages\MSBuildGitHash.0.2.0\build\MSBuildGitHash.props" Condition="Exists('..\packages\MSBuildGitHash.0.2.0\build\MSBuildGitHash.props')" />
  <Import Project="MyMSBuildGitHash.props" />
```

**Comment by MarkPflug** [comment]
You can also disable the validation by adding this property to your project file:

 ```<MSBuildGitHashValidate>False</MSBuildGitHashValidate>```

**Comment by OlegFedko** [comment]
Despite I found how to workaround it, it seems reasonable to make it work with labels by default.
I don't use labels, that one was the only one, made long time ago, I even don't remember about it, but it made a trouble unexpectedly.
By the way, thanks for this package Mark 👍

**Comment by MarkPflug** [comment]
Oleg, just out of curiosity, how did you find this project? Did you find it via nuget?

**Comment by OlegFedko** [comment]
No, I found this answer matching my needs:
https://stackoverflow.com/a/45248069/8669035
It is much simpler than other methods mentioned. Just installing NuGet package, without any Perls, powershells or .exe-s.
