### ISSUE TITLE
The "Exec" task was not given a value for the required parameter "Command"		

### ISSUE THREAD

**Issue by cbade0** [MarkPflug/MSBuildGitHash#12]
On a fresh install of 0.5.0 the build fails with the above error. The build succeeds if I add the MSBuildGitHashCommand to the .csproj, but the README made it seem like that was optional.

**Comment by MarkPflug** [comment]
I can't reproduce the issue you are reporting.

You will get an error on a "fresh install" if it isn't in a valid git repository, but the error will be different.

As far as I can tell, the only way to get the error you are seeing is if you explicitly define MSBuildGitHashCommand to be an empty string.

If you can provide a minimal reproducing project I will take a look at it.

**Comment by cbade0** [comment]
On my main project I reinstalled the nuget package and it worked fine that time. I created a new project and wasn't able to reproduce the issue either after following the same steps I had the first time.  Must have just been some Visual Studio oddity on my machine at the time. Sorry I couldn't be of more help.

I'll close the issue since I wasn't able to replicate the issue.
