### ISSUE TITLE
anyway to disable the AssemblyInformationalVersionAttribute modification

### ISSUE THREAD

**Issue by drdamour** [MarkPflug/MSBuildGitHash#15]
i like the 
```
[assembly: AssemblyMetadata("GitHash"
```

but i do NOT want to modify the AssemblyInformationalVersionAttribute  is there anyway to opt out of that part of this?

**Comment by MarkPflug** [comment]
Thanks for the PR. I just published to nuget 0.5.1 which includes your change.

**Comment by drdamour** [comment]
Sweet!
