### ISSUE TITLE
Default hash fails with tags

### ISSUE THREAD

**Issue by Madpeterz** [MarkPflug/MSBuildGitHash#18]
by default 
> git describe --long --always --dirty

Can use the tags leading to errors
Example:
`MSBuildGitHash hash value starting with 'docker-version-dirty' was invalid.`
that is the shortend value of
`docker-version-0-g662b733-dirty`

this fixs that issue
>git describe --match=NeVeRmAtCh --always --abbrev=7 --dirty

```
<PropertyGroup>
  <MSBuildGitHashCommand>git describe --match=NeVeRmAtCh --always --abbrev=7 --dirty</MSBuildGitHashCommand>
</PropertyGroup>
```

**Comment by MarkPflug** [comment]
Thanks for pointing this out. I've honestly never used tags before.
This appears to work as well, and feels less hacky:
`git describe --exclude=* --always --dirty --abbrev=7`

**Comment by MarkPflug** [comment]
Just pushed nuget 1.0.1 with this fix. Should be available on nuget shortly.

**Comment by xPeyotii** [comment]
> Thanks for pointing this out. I've honestly never used tags before.
> This appears to work as well, and feels less hacky:
> `git describe --exclude=* --always --dirty --abbrev=7`

This is now causing issues for me. JetBrains RIDER won't compile as it gives me the error "unknown option exclude=*". When I remove the --exclude=* it works.
