### ISSUE TITLE
AssemblyMetadataAttribute GitHash not in file properties

### ISSUE THREAD

**Issue by dotnetshadow** [MarkPflug/MSBuildGitHash#23]
Hi there,

When looking at the File properties I see that the GitHash property is missing. Only product version contains the hash
![image](https://user-images.githubusercontent.com/296247/79087126-b9d1a980-7d81-11ea-9661-d97d3a29769d.png)

Using v2.0.1, I was able to access this through "AssemblyMetadataAttribute" with name GitHash
Not sure if something has changed since?

**Comment by MarkPflug** [comment]
That's the expected behavior. The windows Explorer doesn't display any of the .NET specific assembly metadata.

**Comment by dotnetshadow** [comment]
So how can I just get teh githash from the file properties?

I was using this before ```Assembly.GetEntryAssembly()?.GetCustomAttribute<AssemblyMetadataAttribute>().Value;```

Is this not the right way?

**Comment by MarkPflug** [comment]
That's not the right way. There can be multiple `AssemblyMetadatattribute` in your assembly. One will have the key "GitHash".

```
    var gitHash = Assembly
                    .GetEntryAssembly()
                    .GetCustomAttributes<AssemblyMetadataAttribute>()
                    .FirstOrDefault(attr => attr.Key == "GitHash")
                    ?.Value;
```

**Comment by dotnetshadow** [comment]
Ahh ok thank you that's what I was missing cheers, much appreciated
