### ISSUE TITLE
Update issue 1.0.2 -> 2.0.1

### ISSUE THREAD

**Issue by Madpeterz** [MarkPflug/MSBuildGitHash#24]
The following message 
`
fatal: No names found, cannot describe anything.
`
is added to the output when you build, it does not stop the build itself and the version number seems correct, I think this might be looking for a tag and failing if there are none.

the issue goes away if you restore the old version.

**Comment by MarkPflug** [comment]
Unfortunately, I don't know of a way to suppress that message on my end without cutting the feature that causes it. It is, indeed, due to a missing tag. You should be able to add the following to your project file to suppress it though:
```
<ItemGroup>
    <AssemblyMetadataCommand Remove="GitDescription"/>
</ItemGroup>
```

**Comment by Madpeterz** [comment]
This corrects the issue
