### ISSUE TITLE
Multiple commands / outputs

### ISSUE THREAD

**Issue by KoalaBear84** [MarkPflug/MSBuildGitHash#29]
I would like to know if it's possible to combine the output of multiple commands.

git branch --show-current
git rev-list --all --count
git describe --long --always --dirty

Which will create something like:
develop-9657-8f52fbc74-dirty

**Comment by MarkPflug** [comment]
There isn't an easy way to do this within the context of this package. You can add your own custom target to assemble the desired value though.

```xml
  <Target 
    Name="Hack"
    BeforeTargets="GenerateAssemblyAttributes"
    >
    <Exec Command="git branch --show-current" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output PropertyName="OutputA" TaskParameter="ConsoleOutput"/>
    </Exec>

    <Exec Command="git rev-list --all --count" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output PropertyName="OutputB" TaskParameter="ConsoleOutput"/>
    </Exec>

    <Exec Command="git describe --long --always --dirty" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output PropertyName="OutputC" TaskParameter="ConsoleOutput"/>
    </Exec>

    <PropertyGroup>
      <OutputConcat>$(OutputA.Trim())-$(OutputB.Trim())-$(OutputC.Trim())</OutputConcat>
    </PropertyGroup>
    <ItemGroup>
      <AssemblyMetadata Include="MyCustomMetadata">
        <Value>$(OutputConcat)</Value>
      </AssemblyMetadata>
    </ItemGroup>
  </Target>
```

This target is configured to run before the assembly metadata is created. It runs your three comamnds, capturing the output into properties, then concatenating those properties. It then defines an `AssemblyMetadata` item named MyCustomMetadata with the concatenated value. This will cause that metadata to show up in your assembly. You can add that target to a Directory.Build.targets if you want it to apply to multiple projects. Otherwise you can add it directly to your csproj if you only have one project you want to capture the metadata.

Hope that helps.

**Comment by KoalaBear84** [comment]
Thanks Mark! Highly appreciated. 👍

Is it also possible to use that output as the "Product Version"?

**Comment by MarkPflug** [comment]
Do you mean using it as the value of the "AssemblyProduct" assembly attribute?

**Comment by KoalaBear84** [comment]
I think so, the value the plugin adds by 'default'.

**Comment by MarkPflug** [comment]
I think you mean the `AssemblyInformationalVersion`, which is what shows up in explorer when you look at file properties; listed as Product Version.

Yes, that's possible. Requires a few tweaks to the above:

```xml


  <PropertyGroup>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <Target 
    Name="Hack"
    BeforeTargets="GetGitHash;GenerateAssemblyAttributes"
    >
    <Exec Command="git branch --show-current" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output PropertyName="OutputA" TaskParameter="ConsoleOutput"/>
    </Exec>

    <Exec Command="git rev-list --all --count" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output PropertyName="OutputB" TaskParameter="ConsoleOutput"/>
    </Exec>

    <Exec Command="git describe --long --always --dirty" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output PropertyName="OutputC" TaskParameter="ConsoleOutput"/>
    </Exec>

    <PropertyGroup>
      <OutputConcat>$(OutputA.Trim())-$(OutputB.Trim())-$(OutputC.Trim())</OutputConcat>
      <InformationalVersion>$(OutputConcat)</InformationalVersion>
    </PropertyGroup>
    <ItemGroup>
      <AssemblyMetadata Include="MyCustomMetadata">
        <Value>$(OutputConcat)</Value>
      </AssemblyMetadata>
    </ItemGroup>
  </Target>

```

**Comment by MarkPflug** [comment]
And you can delete the part:

```
    <ItemGroup>
      <AssemblyMetadata Include="MyCustomMetadata">
        <Value>$(OutputConcat)</Value>
      </AssemblyMetadata>
    </ItemGroup>
```
As it ends up producing redundant metadata.

**Comment by KoalaBear84** [comment]
Many thanks Mark!

Will try this the day after tomorrow and then close the issue.

**Comment by KoalaBear84** [comment]
We tried to make it work, which it does for ".NET Core", also with the `Directory.Build.targets`.

Unfortunately it does not work for ".NET Framework", which most of the projects still are, and will be for the foreseeable future.

Does it only work for .NET Core projects? Couldn't find anything about it on the Readme, and also the Wiki tab is available, but redirects back to the readme because there is no Wiki behind it.

Thanks in advance!

**Comment by MarkPflug** [comment]
I suspect the difference isn't between ".NET Core" and ".NET Framework", but is really a difference in the project style. Core projects use sdk-style and framework projects often use the old "legacy" style projects. There are differences in how the build process works for these project styles.

Here's what I'd recommend. Stop using the MSBuildGitHash package. Your requirements don't align very well with what this package provides.

Instead, you can manage the construction of the informational version entirely on your own. I've tested that the following code works for both sdk and legacy style projects. It is intended to be used standalone, *without* MSBuildGitHash.

```xml
<Target
    Name="HandleVersions"
    BeforeTargets="CoreCompile;GetAssemblyVersion"
    >
    <Exec Command="git branch --show-current" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output PropertyName="OutputA" TaskParameter="ConsoleOutput"/>
    </Exec>

    <Exec Command="git rev-list --all --count" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output PropertyName="OutputB" TaskParameter="ConsoleOutput"/>
    </Exec>

    <Exec Command="git describe --long --always --dirty" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output PropertyName="OutputC" TaskParameter="ConsoleOutput"/>
    </Exec>

    <PropertyGroup>
      <InformationalVersion>$(OutputA.Trim())-$(OutputB.Trim())-$(OutputC.Trim())</InformationalVersion>
    </PropertyGroup>

    <ItemGroup>
      <AssemblyAttributes
        Include="AssemblyInformationalVersionAttribute">
        <_Parameter1>$(InformationalVersion)</_Parameter1>
      </AssemblyAttributes>
    </ItemGroup>

    <PropertyGroup>
      <VersionAssemblyInfoFile>$(IntermediateOutputDirectory)VersionInfo.cs</VersionAssemblyInfoFile>
    </PropertyGroup>

    <Delete Files="$(VersionAssemblyInfoFile)"/>


    <WriteCodeFragment
      Language="C#"
      Condition="$(UsingMicrosoftNETSdk) != 'true'"
      OutputFile="$(VersionAssemblyInfoFile)"
      AssemblyAttributes="@(AssemblyAttributes)" />

    <ItemGroup>
      <Compile
        Include="$(VersionAssemblyInfoFile)"
        Condition="Exists($(VersionAssemblyInfoFile))"
        />
    </ItemGroup>

  </Target>
```

Hope you can get it working.

**Comment by KoalaBear84** [comment]
You are right, it's a problem of the the csproj style.

The solution works as expected 👍. Didn't knew you can do quite a lot with the tasks.

Thanks you very much!!
