### ISSUE TITLE
Doesn't provide git hash :)

### ISSUE THREAD

**Issue by lsim** [MarkPflug/MSBuildGitHash#4]
Thanks for making this cool package. For those of us that aren't intimate with MSBuild, this is a real time saver.

Given the name of this package, I was somewhat surprised to find that the git hash isn't what is provided. For that you would want to do something like `git rev-parse HEAD` in stead of `git describe`.

It would probably improve the utility of this package if it were possible to override the specific git command used to extract version information. As it stands, I had to include your targets directly in my .csproj and modify the git command there in order to actually get the git hash.

**Comment by MarkPflug** [comment]
You can override the command that is used to produce the "hash" by defining the `MSBuildGitHashCommand` property in your project csproj.
In a PropertyGroup at the top of your project simply add:
```
<PropertyGroup>
...
<MSBuildGitHashCommand>git rev-parse HEAD</MSBuildGitHashCommand>
</PropertyGroup>
```

I'm a git novice, so I'm not familiar with all the commands and terms. My understanding was that the `git describe` output was providing a truncation of the full hash, but would also include an indicator if the local content was not "in-sync", aka `-dirty`.

**Comment by lsim** [comment]
Well, that's a bit embarrassing, isn't it - I missed that completely :)

Thanks for the quick reply and thanks again for making this package public.
