### ISSUE TITLE
Commit not updated if you build from dirty, then commit, then build again

### ISSUE THREAD

**Issue by sashoalm** [MarkPflug/MSBuildGitHash#5]
If I make some changes, then build, then commit and then build again without making additional changes, the Git hash will not be updated. 

This is because without source files being touched the MSBuild Targets will not be executed at all and the project will show "Everything up-to-date".

The best solution would be to check if the HEAD has changed and regenerate the AssemblyInfo.cs only if the commit has changed, but do nothing if the commit wasn't changed.

A slightly worse solution would be to always regenerate but this would break the "Everything up-to-date" - the project will always be built even if nothing was changed including the commit.

**Comment by MarkPflug** [comment]
@sashoalm I just pushed a new version (0.4.1) that I think might fix this issue you were seeing. Let me know if it doesn't and I can take a closer look.

**Comment by rmast** [comment]
Probably it's the same issue I already encountered before:

I altered MSBuildGitHash.props to this regex to make it work:
        `<MSBuildGitHashValidateRegex>^[0-9A-Fa-g\.-]{4,32}(-dirty|-broken)%3F%24</MSBuildGitHashValidateRegex>`
