### ISSUE TITLE
The MSBuildGitHash did not work

### ISSUE THREAD

**Issue by chucklu** [MarkPflug/MSBuildGitHash#8]
Hi,
     

- I have install the nuget package of this project on https://github.com/chucklu/Utility.
     After I build the project, the git hash is not embedded in version of *.dll.
    

- I also tried to run the unit test demo, only the demo for LegacyProjectTest works, SdkProjectTest demo failed with restore error. And the demo project is not a normal one, such as a project have AssemblyInfo.cs .
  

-   I also found you have used git bash in https://github.com/MarkPflug/Elemental.SysInfoTool, I clone this project and build it. When I verify the version, nothing related to git hash.

**Comment by chucklu** [comment]
I found another nuget package to use https://stackoverflow.com/a/41200059/3782855
https://github.com/304NotModified/Fody.Stamp

**Comment by MarkPflug** [comment]
This nuget package doesn't currently set the AssemblyVersion, AssemblyFileVersion or AssemblyInformatinoalVersion. It sets a custom "AssemblyMetadataAttribute" with name GitHash.

I tested it against your "Utility" project, and it worked just fine, the attribute shows up. Same with my SysInfoTool.

I will consider adding AssemblyInformationalVersion in the future.
